app:
  name: ${APP_NAME:LLM Guard API}
  log_level: ${LOG_LEVEL:DEBUG}
  scan_fail_fast: false
  scan_prompt_timeout: 30
  scan_output_timeout: 30
  lazy_load: false

input_scanners:
  - type: Secrets
    params:
      redact_mode: all
  - type: Anonymize
    params:
      language: "tr"
      entity_types:
        - PERSON
        - LOCATION
        - ORGANIZATION
        - EMAIL_ADDRESS_RE
        - TURKISH_PHONE
        - IBAN_TR
        - TC_KIMLIK
        - TAX_NUMBER_TR
        - CREDIT_CARD_RE
        - IP_ADDRESS
        - UUID
        - URL
        - DATE_TIME
        - PHONE_NUMBER
        - CREDIT_CARD
        - IBAN_CODE
        - CRYPTO
        - EMAIL_ADDRESS
      use_faker: false
      threshold: 0.4

output_scanners:
  - type: Deanonymize
